# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-10-21T14:05:24Z"
  labels:
    app: local-web-api
  name: local-web-api
spec:
  containers:
  - image: localhost/webapitestmicroservice:latest
    name: busysanderson
    ports:
    - containerPort: 5204
      hostPort: 5204
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
  restartPolicy: Never
status: {}

